### ISSUE TITLE
Spirit Guardians triggers its animation, but lacks damage automation

### ISSUE THREAD

**Issue by nolorfin** [TheGiddyLimit/plutonium-addon-data#105]
As per the title.

**Comment by TheGiddyLimit** [comment]
Can't reproduce that here; everything looks to be working as-expected:

![image](https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/25264887/8e97ae88-223b-4d1b-a4f0-4b142f0eb6bb)

**Comment by nolorfin** [comment]
I've found that uninstalling DDBImporter fixed this, at least partially. I got it to work yesterday on a combat encounter with 20+ actors, but stopped working at some point. I don't know if this inconsistent behaviour is caused by some module incompatibility or general instability.

**Comment by TheGiddyLimit** [comment]
what's your setup look like in your CPR "Compendium" settings? Both "Additional Compendiums," and "Personal Spell Compendium" compendiums. I _think_ CPR picks some DDBI stuff up by default, so that might be interfering

![image](https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/25264887/4e6f8ec2-9fe4-4cf4-98dc-dbb55edbc242)

**Comment by nolorfin** [comment]
These are my CPR Compendium settings. Chris has mentioned before that his module's prioritisation order should prevent conflicts, but let me know if I should disable anything.
<img width="847" alt="Screenshot 2024-01-01 at 23 13 53" src="https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/72673748/7760ae22-837c-485e-8055-1516f09f47f1">
<img width="804" alt="Screenshot 2024-01-01 at 23 13 35" src="https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/72673748/8fc13660-4ace-4b84-a176-0349ff9e5b44">

**Comment by TheGiddyLimit** [comment]
🤔 that all looks fairly sensible

**Comment by TheGiddyLimit** [comment]
@nolorfin mind testing this, and any other issues you fancy, under the new 0.7.5 release?

**Comment by nolorfin** [comment]
I sure will, but won't be back home until Saturday. Will report what I find ASAP.

**Comment by nolorfin** [comment]
@TheGiddyLimit Both Spirit Guardians' animation and damage are now working after I updated the spell on the character's sheet using CPR's medkit. The spell's icon has changed, though. Instead of showing the dark blue flaming circle, it shows a pale blue vortex, as you can see on the PC's token here.
<img width="707" alt="Screenshot 2024-01-06 at 15 54 04" src="https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/72673748/78a10338-83a3-4e81-93b3-8b58e05ff091">
Targets don't receive the token effect icon when inside the template either.
Besides that, the important parts of the spell seem to be doing their job.

**Comment by TheGiddyLimit** [comment]
I still haven't been able to repro the exact issue you were having, so if you've got a solution which works for you, and things _seem_ like they work for me, then I'm happy to call this case closed

ty for the investigative effort!

**Comment by nolorfin** [comment]
Thank you for looking into it!
