### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by Spappz** [TheGiddyLimit/plutonium-addon-data#19]
Argue and vote on module name:
~~1. Plutonium Add-on: Data~~
~~2. Plutonium Add-on: Effects~~
3. Plutonium Add-on: Content
~~4. Plutonium Add-on: Extras~~
5. Plutonium Add-on: Automation Suite
~~6. Secret Plutonium Add-on: Pretty Power Ztuff~~
7. Plutonium Add-on: The Content patcH
8. Plutonium Add-on: Alternate Content
9. Plutonium Add-on: Full-Auto Mode
10. Plutonium Add-on: Effect Master

More suggestions welcome, but please start vetoing the ones already brought up first 🥺

**Comment by Spappz** [comment]
1 and 2 are soft-vetoed because of the connotations Foundry gives to the words 'data' and 'effect'.
I veto 6 because it's silly (not that self-centred 😏).
I would vote _against_ 4 because it's too generic and doesn't really describe what the add-on does. I'd imagine from the name alone that it added extra functionality, not simply overwrote data to do what you'd expect it to!

Personal vote goes for 5 or some variation with the word 'automation' included; just seems to be the most descriptive option there (and Plutonium As A Service is still funny)

**Comment by revilowaldow** [comment]
Of these I'd pick number 5.

**Comment by TheGiddyLimit** [comment]
5 is nice but I'm going to veto the word "Suite" as it makes my skin crawl

Voting, therefore, for:
5b. Plutonium Add-on: Automation Extras

**Comment by Spappz** [comment]
The 'suite' thing is fair enough. However, with the right Midi settings and a completed dataset it might be able to make you a turkey dinner... The desired end-point is that you can handle about 80% of combat in 5e exactly like a video game, which sounds a bit more than some bells and whistles! This project is going to be pretty monolithic, even if the 'functionality code' is limited---[Midi SRD](https://github.com/kandashi/midi-srd)'s compendiums are already quite substantial, and that's just the SRD.

Something like "Plutonium Automation Add-on" would also sound better to me, fwiw

Also demanding @surged20's attention so we can reach consensus 😎

**Comment by jbowensii** [comment]
I like 5

**Comment by TheGiddyLimit** [comment]
Ye fookit `Plutonium Add-on: Automation` it is
