### ISSUE TITLE
When I installed Plutonium Addon Automation Foundry told me to install Item Macro as a dependency.

### ISSUE THREAD

**Issue by rpganalyst** [TheGiddyLimit/plutonium-addon-data#72]
As the title suggests, I installed Item Macro. When I enabled Plutonium Addon Automation, then, Foundry told me (again) I need to enable Item Macro as well because is a dependency.

Latest plutionum-addon-automation
Foundry v10.291

Thank you

**Comment by TheGiddyLimit** [comment]
That all sounds pretty normal. Is this preventing you from using the module?

**Comment by TheGiddyLimit** [comment]
fair enough. @Spappz I flipped to requiring Item Macro, because even without it, it's still "enabled," just hidden from the user, which feels a bit too sneaky. Unless you have any major objections, I'll update the README to match?

**Comment by Spappz** [comment]
`midi-qol` itself states that it will read `item-macro` flags even in the absence of the module, and you only need the latter enabled if you want to read/edit the macros (in the Foundry GUI). My only real objection is that it's just superfluous JS to load, even if it's only ~16 KB 🥴

I personally think the macros being 'hidden' from the user is 100% fine as long as the README/wiki explains how to see them (both in Foundry and in the source here). After all, I'm pretty sure that `item-macro`, by default, hides the macros from non-GMs anyway! But it isn't a hill I'll die on, so if you want to leave more buttons lying around for non-tech-savvy users to stumble on, go ahead 😏

**Comment by TheGiddyLimit** [comment]
hm true ItemMacro does annoyingly hide itself by default anyway. Guess there's not much point depending on it right enough. Will remove
